def iviBase_CheckAttributeViBoolean(iviBase_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviBase_CheckAttributeViConstString(iviBase_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviBase_CheckAttributeViInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_CheckAttributeViReal64(iviBase_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviBase_CheckAttributeViSession(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_CheckAttributeViUInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_Close(iviBase_vi: int) -> int: ...
def iviBase_GetAttributeRangeMaxValueViBoolean(iviBase_vi: int, channel: str, attributeID: int) -> bool: ...
def iviBase_GetAttributeRangeMaxValueViConstString(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMaxValueViInt32(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMaxValueViReal64(iviBase_vi: int, channel: str, attributeID: int) -> float: ...
def iviBase_GetAttributeRangeMaxValueViSession(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMaxValueViUInt32(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMinValueViBoolean(iviBase_vi: int, channel: str, attributeID: int) -> bool: ...
def iviBase_GetAttributeRangeMinValueViConstString(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMinValueViInt32(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMinValueViReal64(iviBase_vi: int, channel: str, attributeID: int) -> float: ...
def iviBase_GetAttributeRangeMinValueViSession(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeRangeMinValueViUInt32(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeViBoolean(iviBase_vi: int, channel: str, attributeID: int) -> bool: ...
def iviBase_GetAttributeViInt32(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeViReal64(iviBase_vi: int, channel: str, attributeID: int) -> float: ...
def iviBase_GetAttributeViSession(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_GetAttributeViString(iviBase_vi: int, channel: str, attributeID: int) -> str: ...
def iviBase_GetAttributeViUInt32(iviBase_vi: int, channel: str, attributeID: int) -> int: ...
def iviBase_Initialize(logicalName: str, IDQuery: bool, resetDevice: bool, resourceDBPath: str) -> int: ...
def iviBase_Reset(iviBase_vi: int, jsonPath: str) -> int: ...
def iviBase_SaveJson(iviBase_vi: int, iviSavePath: str, icdSavePath: str) -> int: ...
def iviBase_SetAttributeRangeMaxValueViBoolean(iviBase_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviBase_SetAttributeRangeMaxValueViConstString(iviBase_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviBase_SetAttributeRangeMaxValueViInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeRangeMaxValueViReal64(iviBase_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviBase_SetAttributeRangeMaxValueViSession(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeRangeMaxValueViUInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeRangeMinValueViBoolean(iviBase_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviBase_SetAttributeRangeMinValueViConstString(iviBase_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviBase_SetAttributeRangeMinValueViInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeRangeMinValueViReal64(iviBase_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviBase_SetAttributeRangeMinValueViSession(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeRangeMinValueViUInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeViBoolean(iviBase_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviBase_SetAttributeViInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeViReal64(iviBase_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviBase_SetAttributeViSession(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_SetAttributeViString(iviBase_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviBase_SetAttributeViUInt32(iviBase_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviBase_queryAttrID(iviBase_vi: int, attrName: str) -> int: ...
