import numpy

def iviDigitizer_Abort(iviDigitizer_vi: int) -> int: ...
def iviDigitizer_CheckAttributeViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviDigitizer_CheckAttributeViConstString(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviDigitizer_CheckAttributeViInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_CheckAttributeViReal64(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviDigitizer_CheckAttributeViSession(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_CheckAttributeViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_ClearMem(iviDigitizer_vi: int, waveformArray: int) -> int: ...
def iviDigitizer_Close(iviDigitizer_vi: int) -> int: ...
def iviDigitizer_ConfigureAcquisition(iviDigitizer_vi: int, ViConstStringchannelName: str, number_ofRecords: int, recordSize: int, sampleRate: float) -> int: ...
def iviDigitizer_ConfigureChannelDataDepth(iviDigitizer_vi: int, channelName: str, dataDepth: int) -> int: ...
def iviDigitizer_ConfigureChannelDataDepthInt16(iviDigitizer_vi: int, channelName: str, dataDepth: int) -> int: ...
def iviDigitizer_ConfigureChannelDataDepthInt8(iviDigitizer_vi: int, channelName: str, dataDepth: int) -> int: ...
def iviDigitizer_CreateMemInt16(iviDigitizer_vi: int, memDataSize: int) -> int: ...
def iviDigitizer_CreateMemInt8(iviDigitizer_vi: int, memDataSize: int) -> int: ...
def iviDigitizer_FetchWaveformInt16(iviDigitizer_vi: int, channelName: str, waveformArraySize: int) -> numpy.ndarray[numpy.int16]: ...
def iviDigitizer_FetchWaveformInt8(iviDigitizer_vi: int, channelName: str, waveformArraySize: int) -> numpy.ndarray[numpy.int8]: ...
def iviDigitizer_FetchWaveformMemInt16(iviDigitizer_vi: int, channelName: str, waveformArraySize: int, waveformArray: int) -> numpy.ndarray[numpy.int16]: ...
def iviDigitizer_FetchWaveformMemInt8(iviDigitizer_vi: int, channelName: str, waveformArraySize: int, waveformArray: int) -> numpy.ndarray[numpy.int8]: ...
def iviDigitizer_GetAttributeRangeMaxValueViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int) -> bool: ...
def iviDigitizer_GetAttributeRangeMaxValueViConstString(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMaxValueViInt32(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMaxValueViReal64(iviDigitizer_vi: int, channel: str, attributeID: int) -> float: ...
def iviDigitizer_GetAttributeRangeMaxValueViSession(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMaxValueViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMinValueViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int) -> bool: ...
def iviDigitizer_GetAttributeRangeMinValueViConstString(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMinValueViInt32(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMinValueViReal64(iviDigitizer_vi: int, channel: str, attributeID: int) -> float: ...
def iviDigitizer_GetAttributeRangeMinValueViSession(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeRangeMinValueViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int) -> bool: ...
def iviDigitizer_GetAttributeViInt32(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeViReal64(iviDigitizer_vi: int, channel: str, attributeID: int) -> float: ...
def iviDigitizer_GetAttributeViSession(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_GetAttributeViString(iviDigitizer_vi: int, channel: str, attributeID: int) -> str: ...
def iviDigitizer_GetAttributeViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int) -> int: ...
def iviDigitizer_Initialize(logicalName: str, IDQuery: bool, resetDevice: bool, resourceDBPath: str) -> int: ...
def iviDigitizer_InitiateAcquisition(iviDigitizer_vi: int) -> int: ...
def iviDigitizer_ReadWaveformInt16(iviDigitizer_vi: int, channelName: str, waveformArraySize: int, waveformArray: int, maximumTime_ms: float) -> numpy.ndarray[numpy.int16]: ...
def iviDigitizer_ReadWaveformInt8(iviDigitizer_vi: int, channelName: str, waveformArraySize: int, waveformArray: int, maximumTime_ms: float) -> numpy.ndarray[numpy.int8]: ...
def iviDigitizer_Reset(iviDigitizer_vi: int) -> int: ...
def iviDigitizer_SetAttributeRangeMaxValueViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviDigitizer_SetAttributeRangeMaxValueViConstString(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviDigitizer_SetAttributeRangeMaxValueViInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeRangeMaxValueViReal64(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviDigitizer_SetAttributeRangeMaxValueViSession(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeRangeMaxValueViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeRangeMinValueViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviDigitizer_SetAttributeRangeMinValueViConstString(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviDigitizer_SetAttributeRangeMinValueViInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeRangeMinValueViReal64(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviDigitizer_SetAttributeRangeMinValueViSession(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeRangeMinValueViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeViBoolean(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviDigitizer_SetAttributeViInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeViReal64(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviDigitizer_SetAttributeViSession(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_SetAttributeViString(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviDigitizer_SetAttributeViUInt32(iviDigitizer_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviDigitizer_TriggerStart(iviDigitizer_vi: int, channelName: str) -> int: ...
def iviDigitizer_WaitForAcquisitionComplete(iviDigitizer_vi: int, channelName: str, maximumTime_s: float) -> int: ...
