import numpy

def iviFgen_AbortGeneration(iviFgen_vi: int) -> int: ...
def iviFgen_CheckAttributeViBoolean(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviFgen_CheckAttributeViConstString(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviFgen_CheckAttributeViInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_CheckAttributeViReal64(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviFgen_CheckAttributeViSession(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_CheckAttributeViUInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_ClearArbWaveform(iviFgen_vi: int, wfmHandle: int) -> int: ...
def iviFgen_Close(iviFgen_vi: int) -> int: ...
def iviFgen_ConfigureArbWaveformViInt16(iviFgen_vi: int, channelName: str, wfmHandle: int, gain: float, offset: float) -> int: ...
def iviFgen_ConfigureArbWaveformViReal64(iviFgen_vi: int, channelName: str, wfmHandle: int, gain: float, offset: float) -> int: ...
def iviFgen_ConfigureArbWfmMemOffset(iviFgen_vi: int, wfmHandle: int, memOffset: int) -> int: ...
def iviFgen_ConfigureSampleRate(iviFgen_vi: int, sampleRate: float) -> int: ...
def iviFgen_CreateArbWaveformViInt16(iviFgen_vi: int, waveformData: numpy.ndarray[numpy.int16], waveformSize: int) -> int: ...
def iviFgen_CreateArbWaveformViReal64(iviFgen_vi: int, waveformData: numpy.ndarray[numpy.float64], waveformSize: int) -> int: ...
def iviFgen_GetAttributeRangeMaxValueViBoolean(iviFgen_vi: int, channel: str, attributeID: int) -> bool: ...
def iviFgen_GetAttributeRangeMaxValueViConstString(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMaxValueViInt32(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMaxValueViReal64(iviFgen_vi: int, channel: str, attributeID: int) -> float: ...
def iviFgen_GetAttributeRangeMaxValueViSession(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMaxValueViUInt32(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMinValueViBoolean(iviFgen_vi: int, channel: str, attributeID: int) -> bool: ...
def iviFgen_GetAttributeRangeMinValueViConstString(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMinValueViInt32(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMinValueViReal64(iviFgen_vi: int, channel: str, attributeID: int) -> float: ...
def iviFgen_GetAttributeRangeMinValueViSession(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeRangeMinValueViUInt32(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeViBoolean(iviFgen_vi: int, channel: str, attributeID: int) -> bool: ...
def iviFgen_GetAttributeViInt32(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeViReal64(iviFgen_vi: int, channel: str, attributeID: int) -> float: ...
def iviFgen_GetAttributeViSession(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_GetAttributeViString(iviFgen_vi: int, channel: str, attributeID: int) -> str: ...
def iviFgen_GetAttributeViUInt32(iviFgen_vi: int, channel: str, attributeID: int) -> int: ...
def iviFgen_Initialize(logicalName: str, IDQuery: bool, resetDevice: bool, resourceDBPath: str) -> int: ...
def iviFgen_InitiateGeneration(iviFgen_vi: int) -> int: ...
def iviFgen_QueryArbWfmCapabilities(iviFgen_vi: int) -> tuple[int, int, int, int]: ...
def iviFgen_Reset(iviFgen_vi: int) -> int: ...
def iviFgen_SendNSQC(iviFgen_vi: int, NSQCCharData: numpy.ndarray[numpy.int8], NSQCSize: int, NSQCOffset: int = ...) -> int: ...
def iviFgen_SendStream(iviFgen_vi: int, channel: str, streamCharData: numpy.ndarray[numpy.int8], streamSize: int, streamOffset: int) -> int: ...
def iviFgen_SetAttributeRangeMaxValueViBoolean(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviFgen_SetAttributeRangeMaxValueViConstString(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviFgen_SetAttributeRangeMaxValueViInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeRangeMaxValueViReal64(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviFgen_SetAttributeRangeMaxValueViSession(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeRangeMaxValueViUInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeRangeMinValueViBoolean(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviFgen_SetAttributeRangeMinValueViConstString(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviFgen_SetAttributeRangeMinValueViInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeRangeMinValueViReal64(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviFgen_SetAttributeRangeMinValueViSession(iviFgenvi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeRangeMinValueViUInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeViBoolean(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviFgen_SetAttributeViInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeViReal64(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviFgen_SetAttributeViSession(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_SetAttributeViString(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviFgen_SetAttributeViUInt32(iviFgen_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviFgen_Sync(iviFgen_vi: int, iviFgen_vis: numpy.ndarray[numpy.uint64], slave_num: int, cmd_str: str) -> int: ...
