def iviPXIMainBoard_CheckAttributeViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviPXIMainBoard_CheckAttributeViConstString(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviPXIMainBoard_CheckAttributeViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_CheckAttributeViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviPXIMainBoard_CheckAttributeViSession(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_CheckAttributeViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_Close(iviPXIMainBoard_vi: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMaxValueViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> bool: ...
def iviPXIMainBoard_GetAttributeRangeMaxValueViConstString(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMaxValueViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMaxValueViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> float: ...
def iviPXIMainBoard_GetAttributeRangeMaxValueViSession(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMaxValueViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMinValueViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> bool: ...
def iviPXIMainBoard_GetAttributeRangeMinValueViConstString(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMinValueViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMinValueViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> float: ...
def iviPXIMainBoard_GetAttributeRangeMinValueViSession(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeRangeMinValueViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> bool: ...
def iviPXIMainBoard_GetAttributeViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> float: ...
def iviPXIMainBoard_GetAttributeViSession(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_GetAttributeViString(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> str: ...
def iviPXIMainBoard_GetAttributeViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int) -> int: ...
def iviPXIMainBoard_Initialize(logicalName: str, IDQuery: bool, resetDevice: bool, resourceDBPath: str) -> int: ...
def iviPXIMainBoard_Reset(iviPXIMainBoard_vi: int) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMaxValueViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMaxValueViConstString(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMaxValueViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMaxValueViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMaxValueViSession(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMaxValueViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMinValueViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMinValueViConstString(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMinValueViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMinValueViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMinValueViSession(iviPXIMainBoardvi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeRangeMinValueViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeViBoolean(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviPXIMainBoard_SetAttributeViInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeViReal64(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviPXIMainBoard_SetAttributeViSession(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviPXIMainBoard_SetAttributeViString(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviPXIMainBoard_SetAttributeViUInt32(iviPXIMainBoard_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
