def iviSyncATrig_CheckAttributeViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviSyncATrig_CheckAttributeViConstString(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviSyncATrig_CheckAttributeViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_CheckAttributeViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviSyncATrig_CheckAttributeViSession(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_CheckAttributeViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_Close(iviSyncATrig_vi: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMaxValueViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int) -> bool: ...
def iviSyncATrig_GetAttributeRangeMaxValueViConstString(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMaxValueViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMaxValueViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int) -> float: ...
def iviSyncATrig_GetAttributeRangeMaxValueViSession(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMaxValueViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMinValueViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int) -> bool: ...
def iviSyncATrig_GetAttributeRangeMinValueViConstString(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMinValueViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMinValueViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int) -> float: ...
def iviSyncATrig_GetAttributeRangeMinValueViSession(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeRangeMinValueViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int) -> bool: ...
def iviSyncATrig_GetAttributeViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int) -> float: ...
def iviSyncATrig_GetAttributeViSession(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_GetAttributeViString(iviSyncATrig_vi: int, channel: str, attributeID: int) -> str: ...
def iviSyncATrig_GetAttributeViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int) -> int: ...
def iviSyncATrig_Initialize(logicalName: str, IDQuery: bool, resetDevice: bool, resourceDBPath: str) -> int: ...
def iviSyncATrig_Reset(iviSyncATrig_vi: int) -> int: ...
def iviSyncATrig_SetAttributeRangeMaxValueViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviSyncATrig_SetAttributeRangeMaxValueViConstString(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviSyncATrig_SetAttributeRangeMaxValueViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeRangeMaxValueViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviSyncATrig_SetAttributeRangeMaxValueViSession(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeRangeMaxValueViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeRangeMinValueViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviSyncATrig_SetAttributeRangeMinValueViConstString(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviSyncATrig_SetAttributeRangeMinValueViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeRangeMinValueViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviSyncATrig_SetAttributeRangeMinValueViSession(iviSyncATrigvi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeRangeMinValueViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeViBoolean(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: bool) -> int: ...
def iviSyncATrig_SetAttributeViInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeViReal64(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: float) -> int: ...
def iviSyncATrig_SetAttributeViSession(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
def iviSyncATrig_SetAttributeViString(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: str) -> int: ...
def iviSyncATrig_SetAttributeViUInt32(iviSyncATrig_vi: int, channel: str, attributeID: int, attributeValue: int) -> int: ...
