; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; This script installs RIGOL IVI software only (without XDMA driver)
; For XDMA driver installation, use xdma.iss
#define MyAppName "RIGOL_IVI"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "RIGOL Solution"
#define MyAppURL "https://www.rigol.com/"
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{75B2C673-0E62-4099-B9B6-DFEECD8807A0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files\IVI Foundation\IVI\RIGOL
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Require administrator privileges for driver installation
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog
; Custom uninstall program name
UninstallDisplayName={#MyAppName}
UninstallFilesDir={app}\Uninstall_IVI
OutputBaseFilename=RIGOL_IVI_Setup
SolidCompression=yes
WizardStyle=modern
; Install in 64-bit mode on x64 systems to avoid file system redirection
ArchitecturesInstallIn64BitMode=x64
; Show restart reminder after installation (not mandatory)
AlwaysShowDirOnReadyPage=no
AlwaysShowGroupOnReadyPage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
FinishedLabel=Setup has finished installing {#MyAppName} on your computer.%n%nIt is recommended to restart your computer for the environment variables to take effect.%n%nNOTE: Install XDMA driver separately using RIGOL_XDMA_Setup.exe if needed.

[Files]
; Install all files and subdirectories to the target location, maintaining directory structure
; Exclude XDMA driver directory (installed separately by xdma.iss)
Source: "D:\work\SUA_Examples\ivi\win10-C++\Examples\IVI\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "win10xdma"

[Registry]
; Add PythonDLL\Library\bin directory to system environment variable PATH
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\file\PythonDLL\Library\bin"; \
    Flags: preservestringtype; Check: NeedsAddPath('{app}\file\PythonDLL\Library\bin')

[Icons]
Name: "{group}\Uninstall"; Filename: "{uninstallexe}"
Name: "{group}\Enable Test Signing"; Filename: "{app}\EnableTestSigning.bat"; IconFilename: "{sys}\imageres.dll"; IconIndex: 109
Name: "{group}\Disable Test Signing"; Filename: "{app}\DisableTestSigning.bat"; IconFilename: "{sys}\imageres.dll"; IconIndex: 78
Name: "{group}\Check Test Signing Status"; Filename: "{app}\CheckTestSigning.bat"; IconFilename: "{sys}\imageres.dll"; IconIndex: 23

[UninstallDelete]
; Delete dynamically created batch scripts
Type: files; Name: "{app}\EnableTestSigning.bat"
Type: files; Name: "{app}\DisableTestSigning.bat"
Type: files; Name: "{app}\CheckTestSigning.bat"
; Delete custom uninstall directory
Type: filesandordirs; Name: "{app}\Uninstall_IVI"
; Delete runtime generated files and caches from examples
Type: filesandordirs; Name: "{app}\file\conf"
Type: filesandordirs; Name: "{app}\file\wfm"
Type: filesandordirs; Name: "{app}\build"
Type: filesandordirs; Name: "{app}\wfm_file"
Type: filesandordirs; Name: "{app}\Output"
; Delete DAQ generated directories (DAQ-*)
Type: filesandordirs; Name: "{app}\DAQ-*"
; Delete runtime generated files in example directory
Type: filesandordirs; Name: "{app}\example\wfm_file"
Type: filesandordirs; Name: "{app}\example\DAQ-*"
Type: filesandordirs; Name: "{app}\example\conf"
Type: filesandordirs; Name: "{app}\example\build"
Type: filesandordirs; Name: "{app}\example\*.log"
Type: filesandordirs; Name: "{app}\example\*.dat"
Type: filesandordirs; Name: "{app}\example\*.tmp"
; Delete any other generated directories
Type: filesandordirs; Name: "{app}\cmake-build-debug"
Type: filesandordirs; Name: "{app}\cmake-build-release"
Type: filesandordirs; Name: "{app}\Testing"
; Delete generated executable files
Type: files; Name: "{app}\*.exe"
; Delete generated log and temporary files
Type: files; Name: "{app}\*.log"
Type: files; Name: "{app}\*.dat"
Type: files; Name: "{app}\*.tmp"
Type: files; Name: "{app}\*.cache"
; Delete generated data files in subdirectories
Type: filesandordirs; Name: "{app}\file\*.log"
Type: filesandordirs; Name: "{app}\file\*.tmp"

[Run]
; Provide restart option on the finish page
Filename: "{sys}\shutdown.exe"; Parameters: "/r /t 0"; Flags: postinstall runhidden; Description: "Restart computer now (recommended)"


[Code]
// Helper function: Convert boolean to string
function BoolToStr(Value: Boolean): String;
begin
  if Value then
    Result := 'True'
  else
    Result := 'False';
end;

// Helper function: Check if running as administrator
function IsAdmin: Boolean;
begin
  Result := IsAdminLoggedOn or IsPowerUserLoggedOn;
end;

// Helper function: Check if test signing is already enabled
function IsTestSigningEnabled: Boolean;
var
  ResultCode: Integer;
  TempFile: String;
  FileContent: AnsiString;
begin
  Result := False;
  TempFile := ExpandConstant('{tmp}\bcdedit_output.txt');
  
  // Execute bcdedit and save output to file
  if Exec(ExpandConstant('{sys}\bcdedit.exe'), '/enum {current}', TempFile, SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    if FileExists(TempFile) and LoadStringFromFile(TempFile, FileContent) then
    begin
      // Check if testsigning is set to Yes
      if Pos('testsigning', Lowercase(String(FileContent))) > 0 then
      begin
        if Pos('Yes', String(FileContent)) > 0 then
          Result := True;
      end;
      DeleteFile(TempFile);
    end;
  end;
  
  Log('Test signing currently enabled: ' + BoolToStr(Result));
end;

// Get test signing status as string
function GetTestSigningStatus: String;
begin
  if IsTestSigningEnabled then
    Result := 'ENABLED'
  else
    Result := 'DISABLED';
end;

// Helper function: Delete directories matching a pattern (e.g., DAQ-*)
procedure DeleteMatchingDirectories(BasePath: String; Pattern: String);
var
  FindRec: TFindRec;
  FullPath: String;
begin
  Log('Searching for directories matching: ' + Pattern + ' in ' + BasePath);
  
  if FindFirst(BasePath + '\' + Pattern, FindRec) then
  begin
    try
      repeat
        if FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY <> 0 then
        begin
          FullPath := BasePath + '\' + FindRec.Name;
          Log('Found matching directory: ' + FullPath);
          
          if DelTree(FullPath, True, True, True) then
            Log('  Deleted successfully: ' + FindRec.Name)
          else
            Log('  Failed to delete: ' + FindRec.Name);
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end
  else
    Log('No directories matching pattern: ' + Pattern);
end;

// Check if PATH already contains the specified path
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
  ParamExpanded: string;
begin
  // Expand constants in the path
  ParamExpanded := ExpandConstant(Param);
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  // Check if the path already exists (case insensitive)
  Result := Pos(';' + Uppercase(ParamExpanded) + ';', ';' + Uppercase(OrigPath) + ';') = 0;  
  if Result = True then
     Result := Pos(';' + Uppercase(ParamExpanded) + '\;', ';' + Uppercase(OrigPath) + ';') = 0; 
end;

// Create a standalone batch script to enable test signing
procedure CreateEnableTestSignScript;
var
  ScriptPath: String;
  ScriptContent: String;
begin
  ScriptPath := ExpandConstant('{app}') + '\EnableTestSigning.bat';
  
  ScriptContent := '@echo off' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo Enable Test Signing Mode' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo.' + #13#10 +
                  'echo This script will enable test signing mode.' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Test signing mode is required for:' + #13#10 +
                  'echo - Installing unsigned or test-signed drivers' + #13#10 +
                  'echo - XDMA driver installation' + #13#10 +
                  'echo.' + #13#10 +
                  'echo WARNING: This will display "Test Mode" watermark' + #13#10 +
                  'echo on your desktop until disabled.' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Press any key to continue or Ctrl+C to cancel...' + #13#10 +
                  'pause >nul' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Executing: bcdedit /set TESTSIGNING ON' + #13#10 +
                  'bcdedit /set TESTSIGNING ON' + #13#10 +
                  'if errorlevel 1 (' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo ERROR: Failed to enable test signing mode.' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo Possible causes:' + #13#10 +
                  '    echo 1. Not running as administrator' + #13#10 +
                  '    echo 2. Secure Boot is enabled (disable in BIOS)' + #13#10 +
                  '    echo 3. BitLocker is active' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo Please ensure you are running this script as administrator.' + #13#10 +
                  '    echo Right-click the script and select "Run as administrator".' + #13#10 +
                  ') else (' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo ========================================' + #13#10 +
                  '    echo Test signing mode enabled successfully!' + #13#10 +
                  '    echo ========================================' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo IMPORTANT: Please RESTART your computer now!' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo After restart:' + #13#10 +
                  '    echo - "Test Mode" watermark will appear on desktop' + #13#10 +
                  '    echo - Test-signed drivers can be installed' + #13#10 +
                  '    echo - You can proceed with XDMA driver installation' + #13#10 +
                  ')' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Press any key to exit...' + #13#10 +
                  'pause >nul' + #13#10;
  
  SaveStringToFile(ScriptPath, ScriptContent, False);
  Log('Created test signing enable script at: ' + ScriptPath);
end;

// Create a standalone batch script to disable test signing
procedure CreateDisableTestSignScript;
var
  ScriptPath: String;
  ScriptContent: String;
begin
  ScriptPath := ExpandConstant('{app}') + '\DisableTestSigning.bat';
  
  ScriptContent := '@echo off' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo Disable Test Signing Mode' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo.' + #13#10 +
                  'echo This script will disable test signing mode.' + #13#10 +
                  'echo.' + #13#10 +
                  'echo WARNING: Only disable test signing if you have' + #13#10 +
                  'echo no other test-signed drivers installed!' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Press any key to continue or Ctrl+C to cancel...' + #13#10 +
                  'pause >nul' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Executing: bcdedit /set TESTSIGNING OFF' + #13#10 +
                  'bcdedit /set TESTSIGNING OFF' + #13#10 +
                  'if errorlevel 1 (' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo ERROR: Failed to disable test signing mode.' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo Please ensure you are running this script as administrator.' + #13#10 +
                  '    echo Right-click the script and select "Run as administrator".' + #13#10 +
                  ') else (' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo ========================================' + #13#10 +
                  '    echo Test signing mode disabled successfully!' + #13#10 +
                  '    echo ========================================' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo IMPORTANT: Please RESTART your computer now!' + #13#10 +
                  '    echo.' + #13#10 +
                  '    echo After restart:' + #13#10 +
                  '    echo - The "Test Mode" watermark will disappear' + #13#10 +
                  '    echo - Test-signed drivers will no longer load' + #13#10 +
                  ')' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Press any key to exit...' + #13#10 +
                  'pause >nul' + #13#10;
  
  SaveStringToFile(ScriptPath, ScriptContent, False);
  Log('Created test signing disable script at: ' + ScriptPath);
end;

// Create a standalone batch script to check test signing status
procedure CreateCheckTestSignScript;
var
  ScriptPath: String;
  ScriptContent: String;
begin
  ScriptPath := ExpandConstant('{app}') + '\CheckTestSigning.bat';
  
  ScriptContent := '@echo off' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo Check Test Signing Status' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Querying Boot Configuration Data...' + #13#10 +
                  'echo.' + #13#10 +
                  'bcdedit /enum {current} | findstr /i "testsigning"' + #13#10 +
                  'if errorlevel 1 (' + #13#10 +
                  '    echo Test Signing: NOT CONFIGURED (default: DISABLED)' + #13#10 +
                  ') else (' + #13#10 +
                  '    echo.' + #13#10 +
                  ')' + #13#10 +
                  'echo.' + #13#10 +
                  'echo ========================================' + #13#10 +
                  'echo.' + #13#10 +
                  'echo To enable test signing:' + #13#10 +
                  'echo   - Run "Enable Test Signing" from Start Menu' + #13#10 +
                  'echo   - Or execute: bcdedit /set TESTSIGNING ON' + #13#10 +
                  'echo.' + #13#10 +
                  'echo To disable test signing:' + #13#10 +
                  'echo   - Run "Disable Test Signing" from Start Menu' + #13#10 +
                  'echo   - Or execute: bcdedit /set TESTSIGNING OFF' + #13#10 +
                  'echo.' + #13#10 +
                  'echo Press any key to exit...' + #13#10 +
                  'pause >nul' + #13#10;
  
  SaveStringToFile(ScriptPath, ScriptContent, False);
  Log('Created test signing check script at: ' + ScriptPath);
end;

// Post-install actions for IVI
procedure CurStepChanged(CurStep: TSetupStep);
var
  TestSignStatus: String;
  ResultCode: Integer;
  BcdEditPath: String;
  TestSignAlreadyEnabled: Boolean;
begin
  if CurStep = ssPostInstall then
  begin
    // Create utility scripts for test signing management
    CreateEnableTestSignScript;
    CreateDisableTestSignScript;
    CreateCheckTestSignScript;
    
    Log('========================================');
    Log('IVI installation completed');
    Log('Created test signing management scripts');
    Log('========================================');
    
    // Get bcdedit path
    if Is64BitInstallMode then
      BcdEditPath := ExpandConstant('{sys}\bcdedit.exe')
    else
    begin
      BcdEditPath := ExpandConstant('{sysnative}\bcdedit.exe');
      if not FileExists(BcdEditPath) then
        BcdEditPath := ExpandConstant('{sys}\bcdedit.exe');
    end;
    
    // Directly enable test signing mode (no check)
    Log('Enabling test signing mode...');
    Log('Executing: ' + BcdEditPath + ' /set TESTSIGNING ON');
    
    if Exec(BcdEditPath, '/set TESTSIGNING ON', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    begin
      Log('bcdedit executed. Result code: ' + IntToStr(ResultCode));
      
      if ResultCode = 0 then
      begin
        Log('SUCCESS: Test signing mode enabled');
        Log('System restart REQUIRED for test signing to take effect');
        
        MsgBox('RIGOL IVI installation completed successfully!' + #13#10 + #13#10 + 
               '✓ IVI software installed' + #13#10 + 
               '✓ Environment variables configured' + #13#10 + 
               '✓ Test signing mode ENABLED' + #13#10 + 
               '✓ Test signing management tools created' + #13#10 + #13#10 + 
               '═══════════════════════════════════' + #13#10 + 
               'IMPORTANT: RESTART REQUIRED!' + #13#10 + 
               '═══════════════════════════════════' + #13#10 + #13#10 + 
               'Test signing mode has been enabled.' + #13#10 + 
               'You MUST restart your computer for changes to take effect!' + #13#10 + #13#10 + 
               'After restart:' + #13#10 + 
               '  • Desktop will show "Test Mode" watermark' + #13#10 + 
               '  • You can install XDMA driver' + #13#10 + #13#10 + 
               'NOTE: XDMA driver is NOT included in this installation.' + #13#10 + 
               'Please use the separate XDMA installer after restart.' + #13#10 + #13#10 + 
               'You can choose to restart on the next page.', 
               mbInformation, MB_OK);
      end
      else
      begin
        Log('ERROR: Failed to enable test signing. Error code: ' + IntToStr(ResultCode));
        
        if ResultCode = 1 then
        begin
          MsgBox('IVI installation completed, but test signing mode could NOT be enabled!' + #13#10 + #13#10 + 
                 '✓ IVI software installed' + #13#10 + 
                 '✗ Test signing mode NOT enabled' + #13#10 + #13#10 + 
                 '═══════════════════════════════════' + #13#10 + 
                 'POSSIBLE CAUSE: Secure Boot is enabled' + #13#10 + 
                 '═══════════════════════════════════' + #13#10 + #13#10 + 
                 'SOLUTION:' + #13#10 + 
                 '1. Restart computer and enter BIOS/UEFI' + #13#10 + 
                 '   (Press F2/F10/F12/Del during boot)' + #13#10 + 
                 '2. Navigate to Security → Secure Boot' + #13#10 + 
                 '3. Set Secure Boot to [Disabled]' + #13#10 + 
                 '4. Save and Exit (F10)' + #13#10 + 
                 '5. After boot, run from Start Menu:' + #13#10 + 
                 '   RIGOL_IVI → Enable Test Signing' + #13#10 + 
                 '6. Restart computer again', 
                 mbError, MB_OK);
        end
        else
        begin
          MsgBox('IVI installation completed, but test signing mode could NOT be enabled!' + #13#10 + #13#10 + 
                 '✓ IVI software installed' + #13#10 + 
                 '✗ Test signing mode NOT enabled' + #13#10 + 
                 'Error code: ' + IntToStr(ResultCode) + #13#10 + #13#10 + 
                 'You can enable test signing manually:' + #13#10 + 
                 'Start Menu → RIGOL_IVI → Enable Test Signing' + #13#10 + 
                 'Then restart computer.', 
                 mbError, MB_OK);
        end;
      end;
    end
    else
    begin
      Log('ERROR: Failed to execute bcdedit.exe');
      
      MsgBox('IVI installation completed, but test signing mode could NOT be enabled!' + #13#10 + #13#10 + 
             '✓ IVI software installed' + #13#10 + 
             '✗ Test signing mode NOT enabled' + #13#10 + #13#10 + 
             'Failed to execute bcdedit command.' + #13#10 + #13#10 + 
             'You can enable test signing manually:' + #13#10 + 
             'Start Menu → RIGOL_IVI → Enable Test Signing' + #13#10 + 
             'Then restart computer.', 
             mbError, MB_OK);
    end;
  end;
end;

var
  TestSignDisabledDuringUninstall: Boolean;

// Remove path from PATH when uninstalling and disable test signing
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Path: string;
  AppPath: string;
  Offset: Integer;
  ResultCode: Integer;
  BcdEditPath: String;
  TestSignWasEnabled: Boolean;
begin
  if CurUninstallStep = usUninstall then
  begin
    Log('========================================');
    Log('Starting IVI uninstallation...');
    Log('NOTE: XDMA driver is managed separately and will NOT be removed');
    Log('========================================');
    Log('System Information:');
    Log('  - Is 64-bit mode: ' + BoolToStr(Is64BitInstallMode));
    Log('  - {sys} expands to: ' + ExpandConstant('{sys}'));
    Log('  - {sysnative} expands to: ' + ExpandConstant('{sysnative}'));
    
    // Initialize flag
    TestSignDisabledDuringUninstall := False;
    
    // Get bcdedit path
    if Is64BitInstallMode then
      BcdEditPath := ExpandConstant('{sys}\bcdedit.exe')
    else
    begin
      BcdEditPath := ExpandConstant('{sysnative}\bcdedit.exe');
      if not FileExists(BcdEditPath) then
        BcdEditPath := ExpandConstant('{sys}\bcdedit.exe');
    end;
    
    Log('BcdEdit path: ' + BcdEditPath);
    Log('BcdEdit file exists: ' + BoolToStr(FileExists(BcdEditPath)));
    
    if not FileExists(BcdEditPath) then
    begin
      Log('ERROR: bcdedit.exe not found!');
      MsgBox('Error: Cannot find bcdedit.exe' + #13#10 + 
             'Test signing mode cannot be disabled automatically.' + #13#10 + #13#10 + 
             'Please disable manually after uninstall.', 
             mbError, MB_OK);
      Exit;
    end;
    
    Log('========================================');
    Log('Attempting to disable Windows Test Signing Mode...');
    Log('Executing command: ' + BcdEditPath + ' /set TESTSIGNING OFF');
    Log('========================================');
    
    // Always try to disable test signing (will fail gracefully if not enabled)
    if Exec(BcdEditPath, '/set TESTSIGNING OFF', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    begin
      Log('bcdedit executed. Result code: ' + IntToStr(ResultCode));
      
      if ResultCode = 0 then
      begin
        Log('SUCCESS: Test signing mode disabled successfully');
        TestSignDisabledDuringUninstall := True;
      end
      else if ResultCode = 1 then
      begin
        Log('INFO: Test signing was not enabled or already disabled (error code 1)');
        // Error code 1 usually means it was already off or other minor issue
        // Don't show error message, just log it
      end
      else
      begin
        Log('WARNING: Failed to disable test signing. Error code: ' + IntToStr(ResultCode));
        
        MsgBox('IVI uninstallation in progress...' + #13#10 + #13#10 + 
               '⚠ Could not disable test signing mode automatically' + #13#10 + 
               'Error code: ' + IntToStr(ResultCode) + #13#10 + #13#10 + 
               'Possible reasons:' + #13#10 + 
               '  • Test signing is already disabled' + #13#10 + 
               '  • Secure Boot is enabled' + #13#10 + 
               '  • Insufficient permissions' + #13#10 + #13#10 + 
               'You can disable it manually after uninstall:' + #13#10 + 
               '  1. Run Command Prompt as Administrator' + #13#10 + 
               '  2. Execute: bcdedit /set TESTSIGNING OFF' + #13#10 + 
               '  3. Restart computer' + #13#10 + #13#10 + 
               'Uninstallation will continue...', 
               mbInformation, MB_OK);
      end;
    end
    else
    begin
      Log('ERROR: Failed to execute bcdedit.exe at: ' + BcdEditPath);
      
      MsgBox('IVI uninstallation in progress...' + #13#10 + #13#10 + 
             '✗ Could not execute bcdedit command' + #13#10 + #13#10 + 
             'To disable test signing manually:' + #13#10 + 
             '  1. Run Command Prompt as Administrator' + #13#10 + 
             '  2. Execute: bcdedit /set TESTSIGNING OFF' + #13#10 + 
             '  3. Restart computer' + #13#10 + #13#10 + 
             'Uninstallation will continue...', 
             mbInformation, MB_OK);
    end;
  end;
  
  if CurUninstallStep = usPostUninstall then
  begin
    // Remove PATH entry
    AppPath := ExpandConstant('{app}\file\PythonDLL\Library\bin');
    if RegQueryStringValue(HKEY_LOCAL_MACHINE,
      'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
      'Path', Path)
    then begin
      Offset := Pos(';' + Uppercase(AppPath) + ';', ';' + Uppercase(Path) + ';');
      if Offset = 0 then
        Offset := Pos(';' + Uppercase(AppPath) + '\;', ';' + Uppercase(Path) + ';');
      
      if Offset <> 0 then
      begin
        // Remove the path
        StringChangeEx(Path, ';' + AppPath, '', True);
        StringChangeEx(Path, AppPath + ';', '', True);
        RegWriteExpandStringValue(HKEY_LOCAL_MACHINE,
          'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
          'Path', Path);
        Log('Removed PATH entry: ' + AppPath);
      end;
    end;
    
    // Clean up dynamically created files and directories
    Log('Starting cleanup of residual files...');
    
    // Delete batch script files created during installation
    if DeleteFile(ExpandConstant('{app}\EnableTestSigning.bat')) then
      Log('Deleted: EnableTestSigning.bat')
    else
      Log('Could not delete or file not found: EnableTestSigning.bat');
    
    if DeleteFile(ExpandConstant('{app}\DisableTestSigning.bat')) then
      Log('Deleted: DisableTestSigning.bat')
    else
      Log('Could not delete or file not found: DisableTestSigning.bat');
    
    if DeleteFile(ExpandConstant('{app}\CheckTestSigning.bat')) then
      Log('Deleted: CheckTestSigning.bat')
    else
      Log('Could not delete or file not found: CheckTestSigning.bat');
    
    // Delete runtime generated files and caches from examples
    Log('Cleaning up example-generated files...');
    
    if DelTree(ExpandConstant('{app}\file\conf'), True, True, True) then
      Log('Deleted directory: file\conf')
    else
      Log('Directory not found or could not delete: file\conf');
    
    if DelTree(ExpandConstant('{app}\file\wfm'), True, True, True) then
      Log('Deleted directory: file\wfm')
    else
      Log('Directory not found or could not delete: file\wfm');
    
    if DelTree(ExpandConstant('{app}\build'), True, True, True) then
      Log('Deleted directory: build')
    else
      Log('Directory not found or could not delete: build');
    
    if DelTree(ExpandConstant('{app}\wfm_file'), True, True, True) then
      Log('Deleted directory: wfm_file')
    else
      Log('Directory not found or could not delete: wfm_file');
    
    // Delete DAQ-* directories (DAQ generated caches) using pattern matching
    DeleteMatchingDirectories(ExpandConstant('{app}'), 'DAQ-*');
    
    // Delete runtime generated files in example directory
    Log('Cleaning up example directory generated files...');
    
    if DelTree(ExpandConstant('{app}\example\wfm_file'), True, True, True) then
      Log('Deleted directory: example\wfm_file')
    else
      Log('Directory not found or could not delete: example\wfm_file');
    
    // Delete DAQ-* directories in example directory
    DeleteMatchingDirectories(ExpandConstant('{app}\example'), 'DAQ-*');
    
    if DelTree(ExpandConstant('{app}\example\conf'), True, True, True) then
      Log('Deleted directory: example\conf')
    else
      Log('Directory not found or could not delete: example\conf');
    
    if DelTree(ExpandConstant('{app}\example\build'), True, True, True) then
      Log('Deleted directory: example\build')
    else
      Log('Directory not found or could not delete: example\build');
    
    if DelTree(ExpandConstant('{app}\Output'), True, True, True) then
      Log('Deleted directory: Output')
    else
      Log('Directory not found or could not delete: Output');
    
    if DelTree(ExpandConstant('{app}\cmake-build-debug'), True, True, True) then
      Log('Deleted directory: cmake-build-debug')
    else
      Log('Directory not found or could not delete: cmake-build-debug');
    
    if DelTree(ExpandConstant('{app}\cmake-build-release'), True, True, True) then
      Log('Deleted directory: cmake-build-release')
    else
      Log('Directory not found or could not delete: cmake-build-release');
    
    if DelTree(ExpandConstant('{app}\Testing'), True, True, True) then
      Log('Deleted directory: Testing')
    else
      Log('Directory not found or could not delete: Testing');
    
    // Note: Additional wildcard file deletion is handled by [UninstallDelete] section
    Log('Additional cleanup performed by UninstallDelete section');
    
    // Try to remove the main installation directory if empty
    // This will succeed if all subdirectories have been deleted
    if RemoveDir(ExpandConstant('{app}')) then
      Log('Deleted installation directory successfully')
    else
      Log('Installation directory not completely empty - this is normal if subdirectories remain');
      
    Log('Cleanup completed');
    Log('========================================');
    Log('IVI uninstallation completed');
    Log('Test signing disabled: ' + BoolToStr(TestSignDisabledDuringUninstall));
    
    // Show completion message only
    if TestSignDisabledDuringUninstall then
    begin
      Log('Test signing was disabled successfully');
      MsgBox('RIGOL IVI uninstallation completed successfully!' + #13#10 + #13#10 + 
             '✓ IVI software removed' + #13#10 + 
             '✓ Environment variables cleaned' + #13#10 + 
             '✓ Windows Test Signing Mode DISABLED' + #13#10 + #13#10 + 
             '═══════════════════════════════════' + #13#10 + 
             'IMPORTANT: RESTART REQUIRED' + #13#10 + 
             '═══════════════════════════════════' + #13#10 + #13#10 + 
             'Please restart your computer for the test signing' + #13#10 + 
             'mode to be fully disabled.' + #13#10 + #13#10 + 
             'After restart:' + #13#10 + 
             '  • "Test Mode" watermark will disappear' + #13#10 + 
             '  • Test-signed drivers will no longer load' + #13#10 + 
             '  • System returns to normal mode', 
             mbInformation, MB_OK);
    end
    else
    begin
      Log('Test signing was not changed');
      MsgBox('RIGOL IVI uninstallation completed successfully!' + #13#10 + #13#10 + 
             '✓ IVI software removed' + #13#10 + 
             '✓ Environment variables cleaned' + #13#10 + #13#10 + 
             'Uninstallation completed.', 
             mbInformation, MB_OK);
    end;
  end;
end;
