; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "RIGOL_IVI"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "RIGOL Solution"
#define MyAppURL "https://www.rigol.com/"
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{75B2C673-0E62-4099-B9B6-DFEECD8807A0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files\IVI Foundation\IVI\RIGOL
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=RIGOL_IVI_Setup
SolidCompression=yes
WizardStyle=modern
; Show restart reminder after installation (not mandatory)
AlwaysShowDirOnReadyPage=no
AlwaysShowGroupOnReadyPage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
FinishedLabel=Setup has finished installing {#MyAppName} on your computer.%n%nIt is recommended to restart your computer for the environment variables to take effect.

[Files]
; Install all files and subdirectories to the target location, maintaining directory structure
Source: "D:\work\SUA_Examples\ivi\win10-C++\Examples\IVI\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
; Add PythonDLL\Library\bin directory to system environment variable PATH
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\file\PythonDLL\Library\bin"; \
    Flags: preservestringtype; Check: NeedsAddPath('{app}\file\PythonDLL\Library\bin')

[Icons]
Name: "{group}\Uninstall"; Filename: "{uninstallexe}"

[Run]
; Provide restart option on the finish page
Filename: "{sys}\shutdown.exe"; Parameters: "/r /t 0"; Flags: postinstall skipifsilent runhidden; Description: "Restart computer now to make environment variables effective"

[Code]
// Check if PATH already contains the specified path
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
  ParamExpanded: string;
begin
  // Expand constants in the path
  ParamExpanded := ExpandConstant(Param);
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  // Check if the path already exists (case insensitive)
  Result := Pos(';' + Uppercase(ParamExpanded) + ';', ';' + Uppercase(OrigPath) + ';') = 0;  
  if Result = True then
     Result := Pos(';' + Uppercase(ParamExpanded) + '\;', ';' + Uppercase(OrigPath) + ';') = 0; 
end;

// Remove path from PATH when uninstalling
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Path: string;
  AppPath: string;
  Offset: Integer;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    AppPath := ExpandConstant('{app}\file\PythonDLL\Library\bin');
    if RegQueryStringValue(HKEY_LOCAL_MACHINE,
      'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
      'Path', Path)
    then begin
      Offset := Pos(';' + Uppercase(AppPath) + ';', ';' + Uppercase(Path) + ';');
      if Offset = 0 then
        Offset := Pos(';' + Uppercase(AppPath) + '\;', ';' + Uppercase(Path) + ';');
      
      if Offset <> 0 then
      begin
        // Remove the path
        StringChangeEx(Path, ';' + AppPath, '', True);
        StringChangeEx(Path, AppPath + ';', '', True);
        RegWriteExpandStringValue(HKEY_LOCAL_MACHINE,
          'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
          'Path', Path);
      end;
    end;
  end;
end;
