# /*- Completion and Error Codes ----------------------------------------------*/
VI_STATE_SUCCESS                    = 0
VI_STATE_FAIL                       = 1
VI_STATE_TIMEOUT                    = 3
VI_ERROR_MAX_TIME_EXCEEDED          = 4
VI_ERROR_VALUE_OUTPUT_RANGE         = 5
VI_ERROR_ATTR_NO_SCOPE              = 6
VI_ERROR_ATTR_MODULE                = 7
VI_ERROR_ATTR_DATA_TYPE             = 8
VI_ERROR_SYSTEM_STOP                = 9
VI_ERROR_DAQ_FATCH_OVERTIME         =10
VI_ERROR_SAT_REPEAT_CONNECTION      =11
VI_ERROR_RESOURCEDB_NOT_FIND        =12
VI_ERROR_RESOURCEDB_FORMAT_ERROR    =13
VI_ERROR_CS_CR_CONNECTION_FAILED    =14
VI_ERROR_DS_CONNECTION_FAILED           =15
VI_ERROR_JSON_INITIALIZE_FAIL           =16
VI_ERROR_JSON_NOT_FIND                  =17
VI_ERROR_JSON_FORMAT_ERROR              =18
VI_ERROR_VALUE_GET_FAIL                 =19
VI_ERROR_VALUE_SET_FAIL                 =20
VI_ERROR_NO_SUCH_OPERATION              =21
VI_ERROR_ACT_NOT_EXIST                  =22
VI_ERROR_SEQ_FAIL                       =23
VI_ERROR_CHANNEL_ERROR                  =24
VI_ERROR_SEQ_FIND_ACT_FAIL              =25
VI_ERROR_SEQ_EMPTY                      =26
VI_ERROR_ATTR_NOT_SEQ                   =27
VI_ERROR_ATTR_NOT_EXIST                 =28

# /*- Other VISA Definitions --------------------------------------------------*/
VI_STATE_NULL                   = 0
VI_STATE_TRUE                   = 1
VI_STATE_FALSE                  = 0


#/**************IVIBASE_ATTR_REF_CLOCK**************/
IVIBASE_VAL_REF_CLOCK_INT = 0
IVIBASE_VAL_REF_CLOCK_SEL = 1
#/**************IVIBASE_ATTR_REF_CLOCK_SOURCE**************/
IVIBASE_VAL_REF_CLOCK_INTERNAL = 0
IVIBASE_VAL_REF_CLOCK_EXTERNAL = 1
IVIBASE_VAL_REF_CLOCK_RTSI_CLOCK = 2
# /**************IVIBASE_ATTR_REF_SIGNAL_LOCK_STATE**************/
IVIBASE_VAL_REF_SIGNAL_LOCK_STATE_UNLOCK = 0
IVIBASE_VAL_REF_SIGNAL_LOCK_STATE_LOCK = 1
# /**************IVIBASE_ATTR_REF_SIGNAL_EVER_LOST**************/
IVIBASE_VAL_REF_SIGNAL_EVER_LOST_LOSTED = 0
IVIBASE_VAL_REF_SIGNAL_EVER_LOST_UNLOSTRD = 1



#/**************IVIFGEN_ATTR_DAC_PLL_ENABLE**************/
IVIFGEN_VAL_DAC_PLL_SAMPLE_CLOCK = 0
IVIFGEN_VAL_DAC_PLL_REF_CLOCK = 1
#/**************IVIFGEN_ATTR_DAC_NYQ_ZONE**************/
IVIFGEN_VAL_DAC_NYQ_ZONE_1 = 1
IVIFGEN_VAL_DAC_NYQ_ZONE_2 = 2
#/**************IVIFGEN_ATTR_TRIGGER_SOURCE**************/
IVIFGEN_VAL_TRIGGER_SOURCE_INTERNAL = 1<<0
IVIFGEN_VAL_TRIGGER_SOURCE_EXTERNAL = 1<<1
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_STAR_TRIG = 1<<2
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG0 = 1<<3
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG1 = 1<<4
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG2 = 1<<5
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG3 = 1<<6
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG4 = 1<<7
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG5 = 1<<8
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG6 = 1<<9
IVIFGEN_VAL_TRIGGER_SOURCE_PXI_TRIG7 = 1<<10
#/**************IVIFGEN_ATTR_TRIGGER_OUTPUT**************/
IVIFGEN_VAL_TRIGGER_OUTPUT_EXTERNAL = 1<<0
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG0 = 1<<1
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG1 = 1<<2
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG2 = 1<<3
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG3 = 1<<4
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG4 = 1<<5
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG5 = 1<<6
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG6 = 1<<7
IVIFGEN_VAL_TRIGGER_OUTPUT_PXI_TRIG7 = 1<<8
#/**************IVIFGEN_ATTR_OPERATION_MODE**************/
IVIFGEN_VAL_OPERATION_BURST = 1
IVIFGEN_VAL_OPERATION_CONTINUOUS = 2
#/**************IVIFGEN_ATTR_DAC_FUNCTION_CAPABILITIES**************/
IVIFGEN_VAL_DAC_FUNCTION_CAPABILITIES_2O = 2
IVIFGEN_VAL_DAC_FUNCTION_CAPABILITIES_4O = 4
IVIFGEN_VAL_DAC_FUNCTION_CAPABILITIES_8O = 8
#/**************IVIFGEN_ATTR_MNT_CLOCK_INT_SEL**************/
IVIFGEN_VAL_MNT_CLOCK_INT = 0
IVIFGEN_VAL_MNT_CLOCK_SEL = 1
#/**************IVIFGEN_ATTR_SAMPLE_CLOCK_ENABLE**************/
IVIFGEN_VAL_SAMPLE_CLOCK_ENABLE_ON = 0
IVIFGEN_VAL_SAMPLE_CLOCK_ENABLE_OFF = 1
#/**************IVIFGEN_ATTR_DAC_ANTI_SINC_ENABLE**************/
IVIFGEN_VAL_DAC_ANTI_SINC_ENABLE_ON = 0
IVIFGEN_VAL_DAC_ANTI_SINC_ENABLE_OFF = 1
#/**************IVIFGEN_ATTR_WORK_MODE**************/
IVIFGEN_VAL_DAC_WORK_MODE_DDS = 0
IVIFGEN_VAL_DAC_WORK_MODE_RAM = 1
IVIFGEN_VAL_DAC_WORK_MODE_STREAM = 2
IVIFGEN_VAL_DAC_WORK_MODE_SEQ = 3
#/**************IVIFGEN_ATTR_MODULE_DATA_SOURCE**************/
IVIFGEN_VAL_MODULE_DATA_SOURCE_FIBERSEQ = 0
IVIFGEN_VAL_MODULE_DATA_SOURCE_DMA = 1
#/**************IVIFGEN_ATTR_DMA_DESTIONATION_ADDR**************/
IVIFGEN_VAL_MODULE_DATA_SOURCE_MEMORY = 0
IVIFGEN_VAL_MODULE_DATA_SOURCE_P2P = 1
#/**************IVIFGEN_ATTR_COUPLE_TYPE**************/
IVIFGEN_VAL_COUPLE_TYPE_AC = 0
IVIFGEN_VAL_COUPLE_TYPE_AD = 1
#/**************IVIFGEN_ATTR_CHANNEL_QUANTIZATION_METHOD**************/
IVIFGEN_VAL_CHANNEL_QUANTIZATION_METHOD_BIT_8 = 0
IVIFGEN_VAL_CHANNEL_QUANTIZATION_METHOD_BIT_14 = 1
#/**************IVIFGEN_ATTR_WFM_SEG_TYPE**************/
IVIFGEN_VAL_WFM_SEG_TYPE_REAL = 0
IVIFGEN_VAL_WFM_SEG_TYPE_IQ = 1
# /**************IVIFGEN_ATTR_DAC_INTERNAL_MULTIPLE**************/
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_1 = 1
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_2 = 2
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_3 = 3
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_4 = 4
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_5 = 5
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_6 = 6
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_8 = 8
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_10 = 10
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_12 = 12
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_16 = 16
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_20 = 20
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_24 = 24
IVIFGEN_VAL_DAC_INTERNAL_MULTIPLE_40 = 40
# /**************IVIFGEN_ATTR_REF_SIGNAL_LOCK_STATE**************/
IVIFGEN_VAL_REF_SIGNAL_LOCK_STATE_UNLOCK = 0
IVIFGEN_VAL_REF_SIGNAL_LOCK_STATE_LOCK = 1
# /**************IVIFGEN_ATTR_REF_SIGNAL_EVER_LOST**************/
IVIFGEN_VAL_REF_SIGNAL_EVER_LOST_LOSTED = 0
IVIFGEN_VAL_REF_SIGNAL_EVER_LOST_UNLOSTRD = 1
#/**************IVIDIGITIZER_ATTR_ADC_PLL_ENABLE**************/
IVIDIGITIZER_VAL_ADC_PLL_SAMPLE_CLOCK = 0
IVIDIGITIZER_VAL_ADC_PLL_REF_CLOCK = 1
#/**************IVIDIGITIZER_ATTR_ADC_NYQ_ZONE**************/
IVIDIGITIZER_VAL_NYQ_ZONE_1 = 1
IVIDIGITIZER_VAL_NYQ_ZONE_2 = 2
#/**************IVIDIGITIZER_ATTR_TRIGGER_SOURCE**************/
IVIDIGITIZER_VAL_TRIGGER_SOURCE_INTERNAL = 1<<0
IVIDIGITIZER_VAL_TRIGGER_SOURCE_EXTERNAL = 1<<1
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_STAR_TRIG = 1<<2
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG0 = 1<<3
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG1 = 1<<4
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG2 = 1<<5
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG3 = 1<<6
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG4 = 1<<7
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG5 = 1<<8
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG6 = 1<<9
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_TRIG7 = 1<<10
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_LEVEL = 1<<11
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_OR = ~(0<<30)
IVIDIGITIZER_VAL_TRIGGER_SOURCE_PXI_AND = 1<<30
#/**************IVIDIGITIZER_ATTR_TRIGGER_OUTPUT**************/
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_EXTERNAL = 1<<0
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG0 = 1<<1
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG1 = 1<<2
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG2 = 1<<3
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG3 = 1<<4
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG4 = 1<<5
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG5 = 1<<6
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG6 = 1<<7
IVIDIGITIZER_VAL_TRIGGER_OUTPUT_PXI_TRIG7 = 1<<8
#/**************IVIDIGITIZER_ATTR_INTERNAL_TRIGGER_EDGE_TYPE**************/
IVIDIGITIZER_VAL_EDGE_RISING = 0
IVIDIGITIZER_VAL_EDGE_FALLING = 1
#/**************IVIDIGITIZER_ATTR_ADC_FUNCTION_CAPABILITIES**************/
IVIDIGITIZER_VAL_DAC_FUNCTION_CAPABILITIES_1 = 1
IVIDIGITIZER_VAL_DAC_FUNCTION_CAPABILITIES_2 = 2
IVIDIGITIZER_VAL_DAC_FUNCTION_CAPABILITIES_4 = 4
IVIDIGITIZER_VAL_DAC_FUNCTION_CAPABILITIES_8 = 8
#/**************IVIDIGITIZER_ATTR_COUPLE_TYPE**************/
IVIDIGITIZER_VAL_COUPLE_TYPE_DC = 0
IVIDIGITIZER_VAL_COUPLE_TYPE_AC = 1
#/**************IVIDIGITIZER_ATTR_SAMPLE_WORK_MODE**************/
# IVIDIGITIZER_VAL_WORK_MODE_RING = 0
# IVIDIGITIZER_VAL_WORK_MODE_MULTI_SEGMENT = 1
# IVIDIGITIZER_VAL_WORK_MODE_GATE = 2
# IVIDIGITIZER_VAL_WORK_MODE_CONTINUOUS = 3
IVIDIGITIZER_VAL_WORK_MODE_RING_BUFFER = 0
IVIDIGITIZER_VAL_WORK_MODE_MULTI_SEGMENT = 1
IVIDIGITIZER_VAL_WORK_MODE_STREAM = 2
IVIDIGITIZER_VAL_WORK_MODE_GATE = 3
#/**************IVIDIGITIZER_ATTR_PERSIST2DISK_MODE**************/
IVIDIGITIZER_VAL_PERSIST2DISK_MODE_MEMORY = 1
IVIDIGITIZER_VAL_PERSIST2DISK_MODE_P2P = 2
#/**************IVIDIGITIZER_ATTR_SAMPLE_COLLECT_DATA_TRUNCATION**************/
IVIDIGITIZER_VAL_SAMPLE_COLLECT_DATA_TRUNCATION_BIT_14 = 0
IVIDIGITIZER_VAL_SAMPLE_COLLECT_DATA_TRUNCATION_BIT_8 = 1
#/**************IVIDIGITIZER_ATTR_TRIGGER_MODE**************/
IVIDIGITIZER_VAL_TRIGGER_MODE_EDGE = 0
IVIDIGITIZER_VAL_TRIGGER_MODE_WINDOW = 1
#/**************IVIDIGITIZER_ATTR_SAMPLE_TRIGGER_WIN_MODE**************/
IVIDIGITIZER_VAL_SAMPLE_TRIGGER_WIN_MODE_RSTA_FSTP = 0
IVIDIGITIZER_VAL_SAMPLE_TRIGGER_WIN_MODE_FSTA_RSTP = 1
#/**************IVIDIGITIZER_ATTR_REF_SIGNAL_LOCK_STATE**************/
IVIDIGITIZER_VAL_REF_SIGNAL_LOCK_STATE_UNLOCK = 0
IVIDIGITIZER_VAL_REF_SIGNAL_LOCK_STATE_LOCK = 1
#/**************IVIDIGITIZER_ATTR_REF_SIGNAL_EVER_LOST**************/
IVIDIGITIZER_VAL_REF_REF_SIGNAL_EVER_LOST_LOSTED = 0
IVIDIGITIZER_VAL_REF_REF_SIGNAL_EVER_LOST_UNLOSTRD = 1
# /**************IVIDIGITIZER_ATTR_SAMPLE_STATE**************/
IVIDIGITIZER_VAL_SAMPLE_STATE_DONE = 0
IVIDIGITIZER_VAL_SAMPLE_STATE_WAITIN = 1
IVIDIGITIZER_VAL_SAMPLE_STATE_TRIGGERED = 2
# /**************IVIDIGITIZER_ATTR_ADC_EXTRACT_MULTIPLE**************/
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_1 = 1
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_2 = 2
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_3 = 3
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_4 = 4
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_5 = 5
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_6 = 6
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_8 = 8
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_10 = 10
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_12 = 12
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_16 = 16
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_20 = 20
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_24 = 24
IVIDIGITIZER_VAL_ADC_EXTRACT_MULTIPLE_40 = 40
# /**************IVIDIGITIZER_ATTR_SAMPLE_COLLECT_DATA_TYPE**************/
IVIDIGITIZER_VAL_SAMPLE_COLLECT_DATA_TYPE_RE = 0
IVIDIGITIZER_VAL_SAMPLE_COLLECT_DATA_TYPE_COM = 1

# /**************IVIPXIMAINBOARD_ATTR_FAN_SPEED**************/
IVIPXIMAINBOARD_VAL_FAN_SPEED_0 = 0
IVIPXIMAINBOARD_VAL_FAN_SPEED_1 = 1200
IVIPXIMAINBOARD_VAL_FAN_SPEED_2 = 2400
IVIPXIMAINBOARD_VAL_FAN_SPEED_3 = 3600
IVIPXIMAINBOARD_VAL_FAN_SPEED_4 = 4800
IVIPXIMAINBOARD_VAL_FAN_SPEED_5 = 6000
IVIPXIMAINBOARD_VAL_FAN_SPEED_6 = 7200
IVIPXIMAINBOARD_VAL_FAN_SPEED_7 = 8400
IVIPXIMAINBOARD_VAL_FAN_SPEED_8 = 9600
IVIPXIMAINBOARD_VAL_FAN_SPEED_9 = 10800
IVIPXIMAINBOARD_VAL_FAN_SPEED_10 = 12000
# /**************IVIPXIMAINBOARD_ATTR_TRIG_OUT_SOURCE**************/
IVIPXIMAINBOARD_VAL_TRIG_OUT_SOURCE_TRIG_IN = 0
IVIPXIMAINBOARD_VAL_TRIG_OUT_SOURCE_S_PXI_STAR = 1
# /**************IVIPXIMAINBOARD_ATTR_P_PXI_STAR_SOURCE**************/
IVIPXIMAINBOARD_VAL_P_PXI_STAR_SOURCE_TRIG_IN = 0
IVIPXIMAINBOARD_VAL_P_PXI_STAR_SOURCE_S_PXI_STAR = 1
# /**************IVIPXIMAINBOARD_ATTR_CLOCK_10M_SOURCE**************/
IVIPXIMAINBOARD_VAL_CLOCK_10M_SOURCE_IN = 0
IVIPXIMAINBOARD_VAL_P_PXI_10M_SOURCE_OUT = 1
# /**************IVIPXIMAINBOARD_ATTR_CLOCK_100M_SOURCE**************/
IVIPXIMAINBOARD_VAL_CLOCK_100M_SOURCE_IN = 0
IVIPXIMAINBOARD_VAL_P_PXI_100M_SOURCE_OUT = 1
# /**************IVIPXIMAINBOARD_ATTR_FAN_CONTROL**************/
IVIPXIMAINBOARD_VAL_FAN_CONTROL_BOARD = 0
IVIPXIMAINBOARD_VAL_FAN_CONTROL_IVI = 1

# /**************IVISYNCATRIG_ATTR_TEST_CLOCK_SOURCE_100MHZ_RESULT**************/
IVISYNCATRIG_VAL_100MHZ_SOURCE_INTERNAL = 0
IVISYNCATRIG_VAL_100MHZ_SOURCE_EXTERNAL = 1
# /**************IVISYNCATRIG_ATTR_TEST_TRIGGER_OUTPUT_SOURCE**************/
IVISYNCATRIG_VAL_TRIGGER_OUTPUT_SOURCE_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_OUTPUT_SOURCE_EXTERNAL = 1
# /**************IVISYNCATRIG_ATTR_TEST_TRIGGER_SOURCE_P_PXI_STAR**************/
IVISYNCATRIG_VAL_TRIGGER_SOURCE_P_PXI_STAR_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_P_PXI_STAR_EXTERNAL = 1
# /**************IVISYNCATRIG_ATTR_TEST_TRIGGER_SOURCE_PXI_TRIG**************/
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_0_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_0_EXTERNAL = 1<<0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_1_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_1_EXTERNAL = 1<<1
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_2_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_2_EXTERNAL = 1<<2
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_3_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_3_EXTERNAL = 1<<3
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_4_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_4_EXTERNAL = 1<<3
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_5_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_5_EXTERNAL = 1<<4
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_6_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_6_EXTERNAL = 1<<5
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_7_INTERNAL = 0
IVISYNCATRIG_VAL_TRIGGER_SOURCE_PXI_TRIG_7_EXTERNAL = 1<<6

IVIDIGITIZER_VAL_STANDARD_PCKT_HEADER = 0x18EFDC01